### ISSUE TITLE
imagemagick rule fails to build

### ISSUE THREAD

**Issue by robfig** [ahyangyi/astraeus-workspace#1]
Hi, thanks for sharing this. I want to build Imagemagick with Bazel, but it didn't seem to work after cloning your repository, with Bazel 0.19.0. I was wondering if I was doing anything wrong.
Thank you!
Rob

```
$ bazel version
Build label: 0.19.0
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Mon Oct 29 14:34:41 2018 (1540823681)
Build timestamp: 1540823681
Build timestamp as int: 1540823681

$ bazel build '@imagemagick//...'
Starting local Bazel server and connecting to it...
INFO: Analysed 14 targets (16 packages loaded, 1718 targets configured).
INFO: Found 14 targets...
ERROR: /private/var/tmp/_bazel_robfig/00623e8a14cbf65049c404f774523263/external/xz/BUILD.bazel:7:1: C++ compilation of rule '@xz//:lzma' failed (Exit 1) wrapped_clang failed: error executing command external/local_config_cc/wrapped_clang '-D_FORTIFY_SOURCE=1' -fstack-protector -fcolor-diagnostics -Wall -Wthread-safety -Wself-assign -fno-omit-frame-pointer -O0 -DDEBUG -iquote external/xz -iquote ... (remaining 43 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
In file included from external/xz/src/liblzma/common/stream_buffer_decoder.c:13:
In file included from external/xz/src/liblzma/common/stream_decoder.h:16:
external/xz/src/liblzma/common/common.h:35:10: fatal error: 'lzma.h' file not found
#include "lzma.h"
         ^~~~~~~~
1 error generated.
INFO: Elapsed time: 9.501s, Critical Path: 0.84s, Remote (0.00% of the time): [queue: 0.00%, setup: 0.00%, process: 0.00%]
INFO: 3 processes: 3 darwin-sandbox.
FAILED: Build did NOT complete successfully
```

**Comment by ahyangyi** [comment]
The workspace was probably outdated. I'll try updating it to Bazel 0.24.0 when I have time, but unfortunately it seems my Github activity is a bit limited recently...

**Comment by ahyangyi** [comment]
Wow, the path to update is longer than I thought... I'll gradually fix things bit by bit.

**Comment by ahyangyi** [comment]
Hi,

I think I have fixed the various problems encountered when I tried to build it with Bazel 0.24.0.

In particular, the `lzma.h` problem is caused by the lzma actually relying on the **system header**, which completely goes against Bazel's claimed goal of hermeticity. I should find a way to systematically find non-hermetic things in the current workspace, but for now the imagemagick will be buildable again.

Unfortunately I cannot guarantee it also works for Bazel 0.19.0, as Bazel seems to be undergoing major API changes. Hopefully things will stabilize when they reach version 1.0, and we will be really building upon it at that time.
